-- 코드를 입력하세요

WITH RECURSIVE TIMES AS(
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1 FROM TIMES WHERE hour < 23
)

SELECT 
    T.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT
FROM TIMES T
LEFT JOIN ANIMAL_OUTS O
ON HOUR(O.DATETIME)= T.HOUR
GROUP BY T.HOUR
ORDER BY HOUR