-- 코드를 입력하세요
WITH RENTED_CAR AS(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
)

SELECT
    C.CAR_ID,
    CASE WHEN R.CAR_ID IS NOT NULL THEN '대여중'
         ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN RENTED_CAR R
ON C.CAR_ID = R.CAR_ID
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY